# Site settings
title: CafeUI - کافه یو آی
email: mmdsharifi@yahoo.com
description: > # ما یک گروه جوان و پرانرژی طراحی رابط کاربری هستیم که به صورت تیمی پروژه های طراحی را انجام می دهیم.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: cafeui
github_username:  cafeui

# Build settings
markdown: kramdown
#gems:
 # - jalalidate