# Site settings
title: CafeUI - کافه یو آی
email: mmdsharifi@yahoo.com
descrip: ما یک تیم طراحی رابط کاربری وب هستیم.ما در اینجا دانسته هایمان را با شما به اشتراک می گذاریم و در صورت داشتن پروژه ای ما می توانیم شما را کمک کنیم :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: cafeui
github_username:  cafeui

permalink: /:categories/:title.html
exclude: ["node_modules", "assets/scss", "assets/vendor", "gulpfile.js", "package.json", "bower.json", "LICENSE", "Gemfile", "Gemfile.lock"]


# Build settings
markdown: kramdown
#gems:
 # - jalalidate